/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiAiRouteImport } from './routes/api/ai'
import { Route as ApiAiCodeExerciseRouteImport } from './routes/api/ai-code-exercise'
import { Route as ApiAiCurriculumRouteImport } from './routes/api/ai-curriculum'
import { Route as ApiAiDocumentRouteImport } from './routes/api/ai-document'
import { Route as ApiAiFlashcardsRouteImport } from './routes/api/ai-flashcards'
import { Route as ApiAiLessonPlanRouteImport } from './routes/api/ai-lesson-plan'
import { Route as ApiAiPedagogyRouteImport } from './routes/api/ai-pedagogy'
import { Route as ApiAiReviewRouteImport } from './routes/api/ai-review'
import { Route as ApiAiTestRouteImport } from './routes/api/ai-test'
import { Route as ApiAiThemeMetaRouteImport } from './routes/api/ai-theme-meta'
import { Route as ClassClassIdRouteImport } from './routes/class.$classId'
import { Route as ThemeThemeIdRouteImport } from './routes/theme.$themeId'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminActivityRouteImport } from './routes/_authenticated/admin.activity'
import { Route as AuthenticatedAdminAiRouteImport } from './routes/_authenticated/admin.ai'
import { Route as AuthenticatedAdminBackupRouteImport } from './routes/_authenticated/admin.backup'
import { Route as AuthenticatedAdminClassesRouteImport } from './routes/_authenticated/admin.classes'
import { Route as AuthenticatedAdminHelpRouteImport } from './routes/_authenticated/admin.help'
import { Route as AuthenticatedAdminImportRouteImport } from './routes/_authenticated/admin.import'
import { Route as AuthenticatedAdminResourcesRouteImport } from './routes/_authenticated/admin.resources'
import { Route as AuthenticatedAdminScheduleRouteImport } from './routes/_authenticated/admin.schedule'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminSubjectsRouteImport } from './routes/_authenticated/admin.subjects'
import { Route as AuthenticatedAdminThemesRouteImport } from './routes/_authenticated/admin.themes'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as ClassClassIdIndexRouteImport } from './routes/class.$classId.index'
import { Route as TestResourceIdPrintRouteImport } from './routes/test.$resourceId.print'
import { Route as ClassClassIdSubjectSubjectIdRouteImport } from './routes/class.$classId.subject.$subjectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiAiRoute = ApiAiRouteImport.update({
  id: '/api/ai',
  path: '/api/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiCodeExerciseRoute = ApiAiCodeExerciseRouteImport.update({
  id: '/api/ai-code-exercise',
  path: '/api/ai-code-exercise',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiCurriculumRoute = ApiAiCurriculumRouteImport.update({
  id: '/api/ai-curriculum',
  path: '/api/ai-curriculum',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiDocumentRoute = ApiAiDocumentRouteImport.update({
  id: '/api/ai-document',
  path: '/api/ai-document',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiFlashcardsRoute = ApiAiFlashcardsRouteImport.update({
  id: '/api/ai-flashcards',
  path: '/api/ai-flashcards',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiLessonPlanRoute = ApiAiLessonPlanRouteImport.update({
  id: '/api/ai-lesson-plan',
  path: '/api/ai-lesson-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiPedagogyRoute = ApiAiPedagogyRouteImport.update({
  id: '/api/ai-pedagogy',
  path: '/api/ai-pedagogy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiReviewRoute = ApiAiReviewRouteImport.update({
  id: '/api/ai-review',
  path: '/api/ai-review',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiTestRoute = ApiAiTestRouteImport.update({
  id: '/api/ai-test',
  path: '/api/ai-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiThemeMetaRoute = ApiAiThemeMetaRouteImport.update({
  id: '/api/ai-theme-meta',
  path: '/api/ai-theme-meta',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassClassIdRoute = ClassClassIdRouteImport.update({
  id: '/class/$classId',
  path: '/class/$classId',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemeThemeIdRoute = ThemeThemeIdRouteImport.update({
  id: '/theme/$themeId',
  path: '/theme/$themeId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminActivityRoute =
  AuthenticatedAdminActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAiRoute = AuthenticatedAdminAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminBackupRoute =
  AuthenticatedAdminBackupRouteImport.update({
    id: '/backup',
    path: '/backup',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminClassesRoute =
  AuthenticatedAdminClassesRouteImport.update({
    id: '/classes',
    path: '/classes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHelpRoute = AuthenticatedAdminHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminImportRoute =
  AuthenticatedAdminImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminResourcesRoute =
  AuthenticatedAdminResourcesRouteImport.update({
    id: '/resources',
    path: '/resources',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminScheduleRoute =
  AuthenticatedAdminScheduleRouteImport.update({
    id: '/schedule',
    path: '/schedule',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSubjectsRoute =
  AuthenticatedAdminSubjectsRouteImport.update({
    id: '/subjects',
    path: '/subjects',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminThemesRoute =
  AuthenticatedAdminThemesRouteImport.update({
    id: '/themes',
    path: '/themes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ClassClassIdIndexRoute = ClassClassIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClassClassIdRoute,
} as any)
const TestResourceIdPrintRoute = TestResourceIdPrintRouteImport.update({
  id: '/test/$resourceId/print',
  path: '/test/$resourceId/print',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassClassIdSubjectSubjectIdRoute =
  ClassClassIdSubjectSubjectIdRouteImport.update({
    id: '/subject/$subjectId',
    path: '/subject/$subjectId',
    getParentRoute: () => ClassClassIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/api/ai': typeof ApiAiRoute
  '/api/ai-code-exercise': typeof ApiAiCodeExerciseRoute
  '/api/ai-curriculum': typeof ApiAiCurriculumRoute
  '/api/ai-document': typeof ApiAiDocumentRoute
  '/api/ai-flashcards': typeof ApiAiFlashcardsRoute
  '/api/ai-lesson-plan': typeof ApiAiLessonPlanRoute
  '/api/ai-pedagogy': typeof ApiAiPedagogyRoute
  '/api/ai-review': typeof ApiAiReviewRoute
  '/api/ai-test': typeof ApiAiTestRoute
  '/api/ai-theme-meta': typeof ApiAiThemeMetaRoute
  '/class/$classId': typeof ClassClassIdRouteWithChildren
  '/theme/$themeId': typeof ThemeThemeIdRoute
  '/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/admin/ai': typeof AuthenticatedAdminAiRoute
  '/admin/backup': typeof AuthenticatedAdminBackupRoute
  '/admin/classes': typeof AuthenticatedAdminClassesRoute
  '/admin/help': typeof AuthenticatedAdminHelpRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/resources': typeof AuthenticatedAdminResourcesRoute
  '/admin/schedule': typeof AuthenticatedAdminScheduleRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/subjects': typeof AuthenticatedAdminSubjectsRoute
  '/admin/themes': typeof AuthenticatedAdminThemesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/test/$resourceId/print': typeof TestResourceIdPrintRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/class/$classId/': typeof ClassClassIdIndexRoute
  '/class/$classId/subject/$subjectId': typeof ClassClassIdSubjectSubjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/ai': typeof ApiAiRoute
  '/api/ai-code-exercise': typeof ApiAiCodeExerciseRoute
  '/api/ai-curriculum': typeof ApiAiCurriculumRoute
  '/api/ai-document': typeof ApiAiDocumentRoute
  '/api/ai-flashcards': typeof ApiAiFlashcardsRoute
  '/api/ai-lesson-plan': typeof ApiAiLessonPlanRoute
  '/api/ai-pedagogy': typeof ApiAiPedagogyRoute
  '/api/ai-review': typeof ApiAiReviewRoute
  '/api/ai-test': typeof ApiAiTestRoute
  '/api/ai-theme-meta': typeof ApiAiThemeMetaRoute
  '/theme/$themeId': typeof ThemeThemeIdRoute
  '/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/admin/ai': typeof AuthenticatedAdminAiRoute
  '/admin/backup': typeof AuthenticatedAdminBackupRoute
  '/admin/classes': typeof AuthenticatedAdminClassesRoute
  '/admin/help': typeof AuthenticatedAdminHelpRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/resources': typeof AuthenticatedAdminResourcesRoute
  '/admin/schedule': typeof AuthenticatedAdminScheduleRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/subjects': typeof AuthenticatedAdminSubjectsRoute
  '/admin/themes': typeof AuthenticatedAdminThemesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/test/$resourceId/print': typeof TestResourceIdPrintRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/class/$classId': typeof ClassClassIdIndexRoute
  '/class/$classId/subject/$subjectId': typeof ClassClassIdSubjectSubjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/api/ai': typeof ApiAiRoute
  '/api/ai-code-exercise': typeof ApiAiCodeExerciseRoute
  '/api/ai-curriculum': typeof ApiAiCurriculumRoute
  '/api/ai-document': typeof ApiAiDocumentRoute
  '/api/ai-flashcards': typeof ApiAiFlashcardsRoute
  '/api/ai-lesson-plan': typeof ApiAiLessonPlanRoute
  '/api/ai-pedagogy': typeof ApiAiPedagogyRoute
  '/api/ai-review': typeof ApiAiReviewRoute
  '/api/ai-test': typeof ApiAiTestRoute
  '/api/ai-theme-meta': typeof ApiAiThemeMetaRoute
  '/class/$classId': typeof ClassClassIdRouteWithChildren
  '/theme/$themeId': typeof ThemeThemeIdRoute
  '/_authenticated/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/_authenticated/admin/ai': typeof AuthenticatedAdminAiRoute
  '/_authenticated/admin/backup': typeof AuthenticatedAdminBackupRoute
  '/_authenticated/admin/classes': typeof AuthenticatedAdminClassesRoute
  '/_authenticated/admin/help': typeof AuthenticatedAdminHelpRoute
  '/_authenticated/admin/import': typeof AuthenticatedAdminImportRoute
  '/_authenticated/admin/resources': typeof AuthenticatedAdminResourcesRoute
  '/_authenticated/admin/schedule': typeof AuthenticatedAdminScheduleRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/subjects': typeof AuthenticatedAdminSubjectsRoute
  '/_authenticated/admin/themes': typeof AuthenticatedAdminThemesRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/test/$resourceId/print': typeof TestResourceIdPrintRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/class/$classId/': typeof ClassClassIdIndexRoute
  '/class/$classId/subject/$subjectId': typeof ClassClassIdSubjectSubjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/api/ai'
    | '/api/ai-code-exercise'
    | '/api/ai-curriculum'
    | '/api/ai-document'
    | '/api/ai-flashcards'
    | '/api/ai-lesson-plan'
    | '/api/ai-pedagogy'
    | '/api/ai-review'
    | '/api/ai-test'
    | '/api/ai-theme-meta'
    | '/class/$classId'
    | '/theme/$themeId'
    | '/admin/activity'
    | '/admin/ai'
    | '/admin/backup'
    | '/admin/classes'
    | '/admin/help'
    | '/admin/import'
    | '/admin/resources'
    | '/admin/schedule'
    | '/admin/settings'
    | '/admin/subjects'
    | '/admin/themes'
    | '/admin/users'
    | '/test/$resourceId/print'
    | '/admin/'
    | '/class/$classId/'
    | '/class/$classId/subject/$subjectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/api/ai'
    | '/api/ai-code-exercise'
    | '/api/ai-curriculum'
    | '/api/ai-document'
    | '/api/ai-flashcards'
    | '/api/ai-lesson-plan'
    | '/api/ai-pedagogy'
    | '/api/ai-review'
    | '/api/ai-test'
    | '/api/ai-theme-meta'
    | '/theme/$themeId'
    | '/admin/activity'
    | '/admin/ai'
    | '/admin/backup'
    | '/admin/classes'
    | '/admin/help'
    | '/admin/import'
    | '/admin/resources'
    | '/admin/schedule'
    | '/admin/settings'
    | '/admin/subjects'
    | '/admin/themes'
    | '/admin/users'
    | '/test/$resourceId/print'
    | '/admin'
    | '/class/$classId'
    | '/class/$classId/subject/$subjectId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/api/ai'
    | '/api/ai-code-exercise'
    | '/api/ai-curriculum'
    | '/api/ai-document'
    | '/api/ai-flashcards'
    | '/api/ai-lesson-plan'
    | '/api/ai-pedagogy'
    | '/api/ai-review'
    | '/api/ai-test'
    | '/api/ai-theme-meta'
    | '/class/$classId'
    | '/theme/$themeId'
    | '/_authenticated/admin/activity'
    | '/_authenticated/admin/ai'
    | '/_authenticated/admin/backup'
    | '/_authenticated/admin/classes'
    | '/_authenticated/admin/help'
    | '/_authenticated/admin/import'
    | '/_authenticated/admin/resources'
    | '/_authenticated/admin/schedule'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/subjects'
    | '/_authenticated/admin/themes'
    | '/_authenticated/admin/users'
    | '/test/$resourceId/print'
    | '/_authenticated/admin/'
    | '/class/$classId/'
    | '/class/$classId/subject/$subjectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiAiRoute: typeof ApiAiRoute
  ApiAiCodeExerciseRoute: typeof ApiAiCodeExerciseRoute
  ApiAiCurriculumRoute: typeof ApiAiCurriculumRoute
  ApiAiDocumentRoute: typeof ApiAiDocumentRoute
  ApiAiFlashcardsRoute: typeof ApiAiFlashcardsRoute
  ApiAiLessonPlanRoute: typeof ApiAiLessonPlanRoute
  ApiAiPedagogyRoute: typeof ApiAiPedagogyRoute
  ApiAiReviewRoute: typeof ApiAiReviewRoute
  ApiAiTestRoute: typeof ApiAiTestRoute
  ApiAiThemeMetaRoute: typeof ApiAiThemeMetaRoute
  ClassClassIdRoute: typeof ClassClassIdRouteWithChildren
  ThemeThemeIdRoute: typeof ThemeThemeIdRoute
  TestResourceIdPrintRoute: typeof TestResourceIdPrintRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/ai': {
      id: '/api/ai'
      path: '/api/ai'
      fullPath: '/api/ai'
      preLoaderRoute: typeof ApiAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-code-exercise': {
      id: '/api/ai-code-exercise'
      path: '/api/ai-code-exercise'
      fullPath: '/api/ai-code-exercise'
      preLoaderRoute: typeof ApiAiCodeExerciseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-curriculum': {
      id: '/api/ai-curriculum'
      path: '/api/ai-curriculum'
      fullPath: '/api/ai-curriculum'
      preLoaderRoute: typeof ApiAiCurriculumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-document': {
      id: '/api/ai-document'
      path: '/api/ai-document'
      fullPath: '/api/ai-document'
      preLoaderRoute: typeof ApiAiDocumentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-flashcards': {
      id: '/api/ai-flashcards'
      path: '/api/ai-flashcards'
      fullPath: '/api/ai-flashcards'
      preLoaderRoute: typeof ApiAiFlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-lesson-plan': {
      id: '/api/ai-lesson-plan'
      path: '/api/ai-lesson-plan'
      fullPath: '/api/ai-lesson-plan'
      preLoaderRoute: typeof ApiAiLessonPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-pedagogy': {
      id: '/api/ai-pedagogy'
      path: '/api/ai-pedagogy'
      fullPath: '/api/ai-pedagogy'
      preLoaderRoute: typeof ApiAiPedagogyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-review': {
      id: '/api/ai-review'
      path: '/api/ai-review'
      fullPath: '/api/ai-review'
      preLoaderRoute: typeof ApiAiReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-test': {
      id: '/api/ai-test'
      path: '/api/ai-test'
      fullPath: '/api/ai-test'
      preLoaderRoute: typeof ApiAiTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-theme-meta': {
      id: '/api/ai-theme-meta'
      path: '/api/ai-theme-meta'
      fullPath: '/api/ai-theme-meta'
      preLoaderRoute: typeof ApiAiThemeMetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/class/$classId': {
      id: '/class/$classId'
      path: '/class/$classId'
      fullPath: '/class/$classId'
      preLoaderRoute: typeof ClassClassIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theme/$themeId': {
      id: '/theme/$themeId'
      path: '/theme/$themeId'
      fullPath: '/theme/$themeId'
      preLoaderRoute: typeof ThemeThemeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/activity': {
      id: '/_authenticated/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AuthenticatedAdminActivityRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ai': {
      id: '/_authenticated/admin/ai'
      path: '/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AuthenticatedAdminAiRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/backup': {
      id: '/_authenticated/admin/backup'
      path: '/backup'
      fullPath: '/admin/backup'
      preLoaderRoute: typeof AuthenticatedAdminBackupRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/classes': {
      id: '/_authenticated/admin/classes'
      path: '/classes'
      fullPath: '/admin/classes'
      preLoaderRoute: typeof AuthenticatedAdminClassesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/help': {
      id: '/_authenticated/admin/help'
      path: '/help'
      fullPath: '/admin/help'
      preLoaderRoute: typeof AuthenticatedAdminHelpRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/import': {
      id: '/_authenticated/admin/import'
      path: '/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AuthenticatedAdminImportRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/resources': {
      id: '/_authenticated/admin/resources'
      path: '/resources'
      fullPath: '/admin/resources'
      preLoaderRoute: typeof AuthenticatedAdminResourcesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/schedule': {
      id: '/_authenticated/admin/schedule'
      path: '/schedule'
      fullPath: '/admin/schedule'
      preLoaderRoute: typeof AuthenticatedAdminScheduleRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/subjects': {
      id: '/_authenticated/admin/subjects'
      path: '/subjects'
      fullPath: '/admin/subjects'
      preLoaderRoute: typeof AuthenticatedAdminSubjectsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/themes': {
      id: '/_authenticated/admin/themes'
      path: '/themes'
      fullPath: '/admin/themes'
      preLoaderRoute: typeof AuthenticatedAdminThemesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/class/$classId/': {
      id: '/class/$classId/'
      path: '/'
      fullPath: '/class/$classId/'
      preLoaderRoute: typeof ClassClassIdIndexRouteImport
      parentRoute: typeof ClassClassIdRoute
    }
    '/test/$resourceId/print': {
      id: '/test/$resourceId/print'
      path: '/test/$resourceId/print'
      fullPath: '/test/$resourceId/print'
      preLoaderRoute: typeof TestResourceIdPrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/class/$classId/subject/$subjectId': {
      id: '/class/$classId/subject/$subjectId'
      path: '/subject/$subjectId'
      fullPath: '/class/$classId/subject/$subjectId'
      preLoaderRoute: typeof ClassClassIdSubjectSubjectIdRouteImport
      parentRoute: typeof ClassClassIdRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminActivityRoute: typeof AuthenticatedAdminActivityRoute
  AuthenticatedAdminAiRoute: typeof AuthenticatedAdminAiRoute
  AuthenticatedAdminBackupRoute: typeof AuthenticatedAdminBackupRoute
  AuthenticatedAdminClassesRoute: typeof AuthenticatedAdminClassesRoute
  AuthenticatedAdminHelpRoute: typeof AuthenticatedAdminHelpRoute
  AuthenticatedAdminImportRoute: typeof AuthenticatedAdminImportRoute
  AuthenticatedAdminResourcesRoute: typeof AuthenticatedAdminResourcesRoute
  AuthenticatedAdminScheduleRoute: typeof AuthenticatedAdminScheduleRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminSubjectsRoute: typeof AuthenticatedAdminSubjectsRoute
  AuthenticatedAdminThemesRoute: typeof AuthenticatedAdminThemesRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminActivityRoute: AuthenticatedAdminActivityRoute,
  AuthenticatedAdminAiRoute: AuthenticatedAdminAiRoute,
  AuthenticatedAdminBackupRoute: AuthenticatedAdminBackupRoute,
  AuthenticatedAdminClassesRoute: AuthenticatedAdminClassesRoute,
  AuthenticatedAdminHelpRoute: AuthenticatedAdminHelpRoute,
  AuthenticatedAdminImportRoute: AuthenticatedAdminImportRoute,
  AuthenticatedAdminResourcesRoute: AuthenticatedAdminResourcesRoute,
  AuthenticatedAdminScheduleRoute: AuthenticatedAdminScheduleRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminSubjectsRoute: AuthenticatedAdminSubjectsRoute,
  AuthenticatedAdminThemesRoute: AuthenticatedAdminThemesRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ClassClassIdRouteChildren {
  ClassClassIdIndexRoute: typeof ClassClassIdIndexRoute
  ClassClassIdSubjectSubjectIdRoute: typeof ClassClassIdSubjectSubjectIdRoute
}

const ClassClassIdRouteChildren: ClassClassIdRouteChildren = {
  ClassClassIdIndexRoute: ClassClassIdIndexRoute,
  ClassClassIdSubjectSubjectIdRoute: ClassClassIdSubjectSubjectIdRoute,
}

const ClassClassIdRouteWithChildren = ClassClassIdRoute._addFileChildren(
  ClassClassIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiAiRoute: ApiAiRoute,
  ApiAiCodeExerciseRoute: ApiAiCodeExerciseRoute,
  ApiAiCurriculumRoute: ApiAiCurriculumRoute,
  ApiAiDocumentRoute: ApiAiDocumentRoute,
  ApiAiFlashcardsRoute: ApiAiFlashcardsRoute,
  ApiAiLessonPlanRoute: ApiAiLessonPlanRoute,
  ApiAiPedagogyRoute: ApiAiPedagogyRoute,
  ApiAiReviewRoute: ApiAiReviewRoute,
  ApiAiTestRoute: ApiAiTestRoute,
  ApiAiThemeMetaRoute: ApiAiThemeMetaRoute,
  ClassClassIdRoute: ClassClassIdRouteWithChildren,
  ThemeThemeIdRoute: ThemeThemeIdRoute,
  TestResourceIdPrintRoute: TestResourceIdPrintRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
