/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ThemeThemeIdRouteImport } from './routes/theme.$themeId'
import { Route as TestResourceIdRouteImport } from './routes/test.$resourceId'
import { Route as ClassClassIdRouteImport } from './routes/class.$classId'
import { Route as ApiAiTestRouteImport } from './routes/api/ai-test'
import { Route as ApiAiLessonPlanRouteImport } from './routes/api/ai-lesson-plan'
import { Route as ApiAiFlashcardsRouteImport } from './routes/api/ai-flashcards'
import { Route as ApiAiCodeExerciseRouteImport } from './routes/api/ai-code-exercise'
import { Route as ApiAiRouteImport } from './routes/api/ai'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ClassClassIdIndexRouteImport } from './routes/class.$classId.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as TestResourceIdPrintRouteImport } from './routes/test.$resourceId.print'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminThemesRouteImport } from './routes/_authenticated/admin.themes'
import { Route as AuthenticatedAdminSubjectsRouteImport } from './routes/_authenticated/admin.subjects'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminScheduleRouteImport } from './routes/_authenticated/admin.schedule'
import { Route as AuthenticatedAdminResourcesRouteImport } from './routes/_authenticated/admin.resources'
import { Route as AuthenticatedAdminGradesRouteImport } from './routes/_authenticated/admin.grades'
import { Route as AuthenticatedAdminClassesRouteImport } from './routes/_authenticated/admin.classes'
import { Route as AuthenticatedAdminBackupRouteImport } from './routes/_authenticated/admin.backup'
import { Route as AuthenticatedAdminAiRouteImport } from './routes/_authenticated/admin.ai'
import { Route as ClassClassIdSubjectSubjectIdRouteImport } from './routes/class.$classId.subject.$subjectId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemeThemeIdRoute = ThemeThemeIdRouteImport.update({
  id: '/theme/$themeId',
  path: '/theme/$themeId',
  getParentRoute: () => rootRouteImport,
} as any)
const TestResourceIdRoute = TestResourceIdRouteImport.update({
  id: '/test/$resourceId',
  path: '/test/$resourceId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassClassIdRoute = ClassClassIdRouteImport.update({
  id: '/class/$classId',
  path: '/class/$classId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiTestRoute = ApiAiTestRouteImport.update({
  id: '/api/ai-test',
  path: '/api/ai-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiLessonPlanRoute = ApiAiLessonPlanRouteImport.update({
  id: '/api/ai-lesson-plan',
  path: '/api/ai-lesson-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiFlashcardsRoute = ApiAiFlashcardsRouteImport.update({
  id: '/api/ai-flashcards',
  path: '/api/ai-flashcards',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiCodeExerciseRoute = ApiAiCodeExerciseRouteImport.update({
  id: '/api/ai-code-exercise',
  path: '/api/ai-code-exercise',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiRoute = ApiAiRouteImport.update({
  id: '/api/ai',
  path: '/api/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ClassClassIdIndexRoute = ClassClassIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClassClassIdRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const TestResourceIdPrintRoute = TestResourceIdPrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => TestResourceIdRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminThemesRoute =
  AuthenticatedAdminThemesRouteImport.update({
    id: '/themes',
    path: '/themes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSubjectsRoute =
  AuthenticatedAdminSubjectsRouteImport.update({
    id: '/subjects',
    path: '/subjects',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminScheduleRoute =
  AuthenticatedAdminScheduleRouteImport.update({
    id: '/schedule',
    path: '/schedule',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminResourcesRoute =
  AuthenticatedAdminResourcesRouteImport.update({
    id: '/resources',
    path: '/resources',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminGradesRoute =
  AuthenticatedAdminGradesRouteImport.update({
    id: '/grades',
    path: '/grades',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminClassesRoute =
  AuthenticatedAdminClassesRouteImport.update({
    id: '/classes',
    path: '/classes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBackupRoute =
  AuthenticatedAdminBackupRouteImport.update({
    id: '/backup',
    path: '/backup',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAiRoute = AuthenticatedAdminAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ClassClassIdSubjectSubjectIdRoute =
  ClassClassIdSubjectSubjectIdRouteImport.update({
    id: '/subject/$subjectId',
    path: '/subject/$subjectId',
    getParentRoute: () => ClassClassIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/api/ai': typeof ApiAiRoute
  '/api/ai-code-exercise': typeof ApiAiCodeExerciseRoute
  '/api/ai-flashcards': typeof ApiAiFlashcardsRoute
  '/api/ai-lesson-plan': typeof ApiAiLessonPlanRoute
  '/api/ai-test': typeof ApiAiTestRoute
  '/class/$classId': typeof ClassClassIdRouteWithChildren
  '/test/$resourceId': typeof TestResourceIdRouteWithChildren
  '/theme/$themeId': typeof ThemeThemeIdRoute
  '/admin/ai': typeof AuthenticatedAdminAiRoute
  '/admin/backup': typeof AuthenticatedAdminBackupRoute
  '/admin/classes': typeof AuthenticatedAdminClassesRoute
  '/admin/grades': typeof AuthenticatedAdminGradesRoute
  '/admin/resources': typeof AuthenticatedAdminResourcesRoute
  '/admin/schedule': typeof AuthenticatedAdminScheduleRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/subjects': typeof AuthenticatedAdminSubjectsRoute
  '/admin/themes': typeof AuthenticatedAdminThemesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/test/$resourceId/print': typeof TestResourceIdPrintRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/class/$classId/': typeof ClassClassIdIndexRoute
  '/class/$classId/subject/$subjectId': typeof ClassClassIdSubjectSubjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/ai': typeof ApiAiRoute
  '/api/ai-code-exercise': typeof ApiAiCodeExerciseRoute
  '/api/ai-flashcards': typeof ApiAiFlashcardsRoute
  '/api/ai-lesson-plan': typeof ApiAiLessonPlanRoute
  '/api/ai-test': typeof ApiAiTestRoute
  '/test/$resourceId': typeof TestResourceIdRouteWithChildren
  '/theme/$themeId': typeof ThemeThemeIdRoute
  '/admin/ai': typeof AuthenticatedAdminAiRoute
  '/admin/backup': typeof AuthenticatedAdminBackupRoute
  '/admin/classes': typeof AuthenticatedAdminClassesRoute
  '/admin/grades': typeof AuthenticatedAdminGradesRoute
  '/admin/resources': typeof AuthenticatedAdminResourcesRoute
  '/admin/schedule': typeof AuthenticatedAdminScheduleRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/subjects': typeof AuthenticatedAdminSubjectsRoute
  '/admin/themes': typeof AuthenticatedAdminThemesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/test/$resourceId/print': typeof TestResourceIdPrintRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/class/$classId': typeof ClassClassIdIndexRoute
  '/class/$classId/subject/$subjectId': typeof ClassClassIdSubjectSubjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/api/ai': typeof ApiAiRoute
  '/api/ai-code-exercise': typeof ApiAiCodeExerciseRoute
  '/api/ai-flashcards': typeof ApiAiFlashcardsRoute
  '/api/ai-lesson-plan': typeof ApiAiLessonPlanRoute
  '/api/ai-test': typeof ApiAiTestRoute
  '/class/$classId': typeof ClassClassIdRouteWithChildren
  '/test/$resourceId': typeof TestResourceIdRouteWithChildren
  '/theme/$themeId': typeof ThemeThemeIdRoute
  '/_authenticated/admin/ai': typeof AuthenticatedAdminAiRoute
  '/_authenticated/admin/backup': typeof AuthenticatedAdminBackupRoute
  '/_authenticated/admin/classes': typeof AuthenticatedAdminClassesRoute
  '/_authenticated/admin/grades': typeof AuthenticatedAdminGradesRoute
  '/_authenticated/admin/resources': typeof AuthenticatedAdminResourcesRoute
  '/_authenticated/admin/schedule': typeof AuthenticatedAdminScheduleRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/subjects': typeof AuthenticatedAdminSubjectsRoute
  '/_authenticated/admin/themes': typeof AuthenticatedAdminThemesRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/test/$resourceId/print': typeof TestResourceIdPrintRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/class/$classId/': typeof ClassClassIdIndexRoute
  '/class/$classId/subject/$subjectId': typeof ClassClassIdSubjectSubjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/api/ai'
    | '/api/ai-code-exercise'
    | '/api/ai-flashcards'
    | '/api/ai-lesson-plan'
    | '/api/ai-test'
    | '/class/$classId'
    | '/test/$resourceId'
    | '/theme/$themeId'
    | '/admin/ai'
    | '/admin/backup'
    | '/admin/classes'
    | '/admin/grades'
    | '/admin/resources'
    | '/admin/schedule'
    | '/admin/settings'
    | '/admin/subjects'
    | '/admin/themes'
    | '/admin/users'
    | '/test/$resourceId/print'
    | '/admin/'
    | '/class/$classId/'
    | '/class/$classId/subject/$subjectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/api/ai'
    | '/api/ai-code-exercise'
    | '/api/ai-flashcards'
    | '/api/ai-lesson-plan'
    | '/api/ai-test'
    | '/test/$resourceId'
    | '/theme/$themeId'
    | '/admin/ai'
    | '/admin/backup'
    | '/admin/classes'
    | '/admin/grades'
    | '/admin/resources'
    | '/admin/schedule'
    | '/admin/settings'
    | '/admin/subjects'
    | '/admin/themes'
    | '/admin/users'
    | '/test/$resourceId/print'
    | '/admin'
    | '/class/$classId'
    | '/class/$classId/subject/$subjectId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/api/ai'
    | '/api/ai-code-exercise'
    | '/api/ai-flashcards'
    | '/api/ai-lesson-plan'
    | '/api/ai-test'
    | '/class/$classId'
    | '/test/$resourceId'
    | '/theme/$themeId'
    | '/_authenticated/admin/ai'
    | '/_authenticated/admin/backup'
    | '/_authenticated/admin/classes'
    | '/_authenticated/admin/grades'
    | '/_authenticated/admin/resources'
    | '/_authenticated/admin/schedule'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/subjects'
    | '/_authenticated/admin/themes'
    | '/_authenticated/admin/users'
    | '/test/$resourceId/print'
    | '/_authenticated/admin/'
    | '/class/$classId/'
    | '/class/$classId/subject/$subjectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiAiRoute: typeof ApiAiRoute
  ApiAiCodeExerciseRoute: typeof ApiAiCodeExerciseRoute
  ApiAiFlashcardsRoute: typeof ApiAiFlashcardsRoute
  ApiAiLessonPlanRoute: typeof ApiAiLessonPlanRoute
  ApiAiTestRoute: typeof ApiAiTestRoute
  ClassClassIdRoute: typeof ClassClassIdRouteWithChildren
  TestResourceIdRoute: typeof TestResourceIdRouteWithChildren
  ThemeThemeIdRoute: typeof ThemeThemeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theme/$themeId': {
      id: '/theme/$themeId'
      path: '/theme/$themeId'
      fullPath: '/theme/$themeId'
      preLoaderRoute: typeof ThemeThemeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/$resourceId': {
      id: '/test/$resourceId'
      path: '/test/$resourceId'
      fullPath: '/test/$resourceId'
      preLoaderRoute: typeof TestResourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/class/$classId': {
      id: '/class/$classId'
      path: '/class/$classId'
      fullPath: '/class/$classId'
      preLoaderRoute: typeof ClassClassIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-test': {
      id: '/api/ai-test'
      path: '/api/ai-test'
      fullPath: '/api/ai-test'
      preLoaderRoute: typeof ApiAiTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-lesson-plan': {
      id: '/api/ai-lesson-plan'
      path: '/api/ai-lesson-plan'
      fullPath: '/api/ai-lesson-plan'
      preLoaderRoute: typeof ApiAiLessonPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-flashcards': {
      id: '/api/ai-flashcards'
      path: '/api/ai-flashcards'
      fullPath: '/api/ai-flashcards'
      preLoaderRoute: typeof ApiAiFlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-code-exercise': {
      id: '/api/ai-code-exercise'
      path: '/api/ai-code-exercise'
      fullPath: '/api/ai-code-exercise'
      preLoaderRoute: typeof ApiAiCodeExerciseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai': {
      id: '/api/ai'
      path: '/api/ai'
      fullPath: '/api/ai'
      preLoaderRoute: typeof ApiAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/class/$classId/': {
      id: '/class/$classId/'
      path: '/'
      fullPath: '/class/$classId/'
      preLoaderRoute: typeof ClassClassIdIndexRouteImport
      parentRoute: typeof ClassClassIdRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/test/$resourceId/print': {
      id: '/test/$resourceId/print'
      path: '/print'
      fullPath: '/test/$resourceId/print'
      preLoaderRoute: typeof TestResourceIdPrintRouteImport
      parentRoute: typeof TestResourceIdRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/themes': {
      id: '/_authenticated/admin/themes'
      path: '/themes'
      fullPath: '/admin/themes'
      preLoaderRoute: typeof AuthenticatedAdminThemesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/subjects': {
      id: '/_authenticated/admin/subjects'
      path: '/subjects'
      fullPath: '/admin/subjects'
      preLoaderRoute: typeof AuthenticatedAdminSubjectsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/schedule': {
      id: '/_authenticated/admin/schedule'
      path: '/schedule'
      fullPath: '/admin/schedule'
      preLoaderRoute: typeof AuthenticatedAdminScheduleRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/resources': {
      id: '/_authenticated/admin/resources'
      path: '/resources'
      fullPath: '/admin/resources'
      preLoaderRoute: typeof AuthenticatedAdminResourcesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/grades': {
      id: '/_authenticated/admin/grades'
      path: '/grades'
      fullPath: '/admin/grades'
      preLoaderRoute: typeof AuthenticatedAdminGradesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/classes': {
      id: '/_authenticated/admin/classes'
      path: '/classes'
      fullPath: '/admin/classes'
      preLoaderRoute: typeof AuthenticatedAdminClassesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/backup': {
      id: '/_authenticated/admin/backup'
      path: '/backup'
      fullPath: '/admin/backup'
      preLoaderRoute: typeof AuthenticatedAdminBackupRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ai': {
      id: '/_authenticated/admin/ai'
      path: '/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AuthenticatedAdminAiRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/class/$classId/subject/$subjectId': {
      id: '/class/$classId/subject/$subjectId'
      path: '/subject/$subjectId'
      fullPath: '/class/$classId/subject/$subjectId'
      preLoaderRoute: typeof ClassClassIdSubjectSubjectIdRouteImport
      parentRoute: typeof ClassClassIdRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAiRoute: typeof AuthenticatedAdminAiRoute
  AuthenticatedAdminBackupRoute: typeof AuthenticatedAdminBackupRoute
  AuthenticatedAdminClassesRoute: typeof AuthenticatedAdminClassesRoute
  AuthenticatedAdminGradesRoute: typeof AuthenticatedAdminGradesRoute
  AuthenticatedAdminResourcesRoute: typeof AuthenticatedAdminResourcesRoute
  AuthenticatedAdminScheduleRoute: typeof AuthenticatedAdminScheduleRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminSubjectsRoute: typeof AuthenticatedAdminSubjectsRoute
  AuthenticatedAdminThemesRoute: typeof AuthenticatedAdminThemesRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAiRoute: AuthenticatedAdminAiRoute,
  AuthenticatedAdminBackupRoute: AuthenticatedAdminBackupRoute,
  AuthenticatedAdminClassesRoute: AuthenticatedAdminClassesRoute,
  AuthenticatedAdminGradesRoute: AuthenticatedAdminGradesRoute,
  AuthenticatedAdminResourcesRoute: AuthenticatedAdminResourcesRoute,
  AuthenticatedAdminScheduleRoute: AuthenticatedAdminScheduleRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminSubjectsRoute: AuthenticatedAdminSubjectsRoute,
  AuthenticatedAdminThemesRoute: AuthenticatedAdminThemesRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ClassClassIdRouteChildren {
  ClassClassIdIndexRoute: typeof ClassClassIdIndexRoute
  ClassClassIdSubjectSubjectIdRoute: typeof ClassClassIdSubjectSubjectIdRoute
}

const ClassClassIdRouteChildren: ClassClassIdRouteChildren = {
  ClassClassIdIndexRoute: ClassClassIdIndexRoute,
  ClassClassIdSubjectSubjectIdRoute: ClassClassIdSubjectSubjectIdRoute,
}

const ClassClassIdRouteWithChildren = ClassClassIdRoute._addFileChildren(
  ClassClassIdRouteChildren,
)

interface TestResourceIdRouteChildren {
  TestResourceIdPrintRoute: typeof TestResourceIdPrintRoute
}

const TestResourceIdRouteChildren: TestResourceIdRouteChildren = {
  TestResourceIdPrintRoute: TestResourceIdPrintRoute,
}

const TestResourceIdRouteWithChildren = TestResourceIdRoute._addFileChildren(
  TestResourceIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiAiRoute: ApiAiRoute,
  ApiAiCodeExerciseRoute: ApiAiCodeExerciseRoute,
  ApiAiFlashcardsRoute: ApiAiFlashcardsRoute,
  ApiAiLessonPlanRoute: ApiAiLessonPlanRoute,
  ApiAiTestRoute: ApiAiTestRoute,
  ClassClassIdRoute: ClassClassIdRouteWithChildren,
  TestResourceIdRoute: TestResourceIdRouteWithChildren,
  ThemeThemeIdRoute: ThemeThemeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
